[tool.poetry]
name = "cbfkit"
version = "0.1.0"
description = "A Control Barrier Function Toolbox for Robotics Applications"
authors = ["Bardh Hoxha <bardhh@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include="cbfkit", from="src"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.24.2"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
sympy = "^1.11.1"
control = "^0.9.3.post2"
kvxopt = {version = "^1.3.0.3", platform = "darwin"}
cvxopt = {version = "~1.2", platform = "linux"}
jaxlib = { extras = ["gpu"], version = "^0.4.7" }
jax = "^0.4.7"
tail-recursion = "^1.1.1"
tail-recursive = "^2.1.0"
black = "^23.3.0"
pandas = "^2.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length=100
skip_gitignore = true
